image: python:3.6.1

pipelines:
  default:
    - step:
        script:
          - pip install -U tox
          - pip install -I --no-use-wheel capstone
          - apt-get install python-capstone
          - tox
