image: python:3.7

pipelines:
  default:
    - step:
        caches:
          - pip
        script:
          - pip install pipenv
          - export PIP_PROCESS_DEPENDENCY_LINKS=1
          - pipenv install --dev
          - pipenv run invoke deps
          - pipenv run invoke install
          - pipenv run invoke test
        script:
          - pip install invoke pipenv
          # XXX(PT): Does this break installing strongarm via pip on a fresh machine?
          # We might still need setup.py to install Capstone.
          - invoke deps
          - python setup.py install
          - invoke test
