image: python:3.7

pipelines:
  default:
    - parallel:
      - step:
          name: Code linting
          caches:
            - pip
          script:
            - pip install -U pip wheel setuptools 'pip-tools<7.0.0'
            - pip-sync requirements.txt requirements-dev.txt
            - invoke install
            - invoke autoformat-lint
      - step:
          name: Test (via Pipenv)
          caches:
            - pip
          script:
            # Update before installing packages
            - apt-get update
            # These dependencies are normally installed by strongarm-base/setup.py
            - apt-get install libcapstone4 libcapstone-dev sqlite3 libsqlite3-dev -y --allow-unauthenticated
            - pip install -U pip wheel setuptools 'pip-tools<7.0.0'
            - pip-sync requirements.txt requirements-dev.txt
            - invoke install
            - invoke test
      - step:
          name: Test (via setuptools)
          caches:
            - pip
          script:
            # Update before installing packages
            - apt-get update
            # These dependencies are normally installed by strongarm-base/setup.py
            - apt-get install libcapstone4 libcapstone-dev sqlite3 libsqlite3-dev libffi-dev -y --allow-unauthenticated
            - pip install invoke mypy flake8 pytest pytest-xdist
            # Version info
            - python --version
            - pip --version
            # Use pip instead of `python setup.py install`. For some reason, Pip can handle the git dependencies, but
            # not `setup.py install`, even if setuptools is fully up-to-date?
            #
            # Using pip and not pipenv here to ensure that setup.py's deps are what is used
            - pip install .
            - invoke test
