image: python:3.6-stretch

pipelines:
  default:
    - step:
        script:
          - pip install -r requirements.txt
          - python setup.py install
          # Build the dataflow module
          - python setup.py build_ext --inplace
          - pytest
