image: python:3.7

pipelines:
  default:
    - parallel:
      - step:
          name: Code linting
          caches:
            - pip
          script:
            - pip install pipenv
            - export PIP_PROCESS_DEPENDENCY_LINKS=1
            - pipenv install --dev
            - pipenv run invoke install
            - pipenv run invoke autoformat-lint
      - step:
          name: Test code
          caches:
            - pip
          script:
            - pip install pipenv
            - export PIP_PROCESS_DEPENDENCY_LINKS=1
            - pipenv install --dev
            - pipenv run invoke install
            - pipenv run invoke test
      - step:
          name: Test installation
          caches:
            - pip
          script:
            - pip install invoke pipenv pytest mypy flake8
            - python setup.py install
            - invoke test
