image: python:3.7

pipelines:
  default:
    - step:
        caches:
          - pip
        script:
          - pip install pipenv
          - export PIP_PROCESS_DEPENDENCY_LINKS=1
          - pipenv install --dev
          - pipenv run invoke deps
          - pipenv run invoke install
          - pipenv run invoke test
